/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iSfsKtvFhGH
 */
import { CardTitle, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function FormCards() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <Card className="rounded-lg shadow-lg overflow-hidden">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <CardTitle className="font-semibold">Form Title 1</CardTitle>
            <svg
              className=" h-6 w-6 text-zinc-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect height="12" rx="2" width="20" x="2" y="6" />
              <path d="M12 12h.01" />
              <path d="M17 12h.01" />
              <path d="M7 12h.01" />
            </svg>
          </div>
          <p className="text-sm text-zinc-500 mt-2">This is a snippet of the content for Form 1...</p>
          <p className="text-xs text-zinc-400 mt-4">Last modified: 18 Nov 2023</p>
          <Button className="mt-4" variant="outline">
            Open Form
          </Button>
        </CardContent>
      </Card>
      <Card className="rounded-lg shadow-lg overflow-hidden">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <CardTitle className="font-semibold">Form Title 2</CardTitle>
            <svg
              className=" h-6 w-6 text-zinc-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect height="12" rx="2" width="20" x="2" y="6" />
              <path d="M12 12h.01" />
              <path d="M17 12h.01" />
              <path d="M7 12h.01" />
            </svg>
          </div>
          <p className="text-sm text-zinc-500 mt-2">This is a snippet of the content for Form 2...</p>
          <p className="text-xs text-zinc-400 mt-4">Last modified: 17 Nov 2023</p>
          <Button className="mt-4" variant="outline">
            Open Form
          </Button>
        </CardContent>
      </Card>
      <Card className="rounded-lg shadow-lg overflow-hidden">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <CardTitle className="font-semibold">Form Title 3</CardTitle>
            <svg
              className=" h-6 w-6 text-zinc-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect height="12" rx="2" width="20" x="2" y="6" />
              <path d="M12 12h.01" />
              <path d="M17 12h.01" />
              <path d="M7 12h.01" />
            </svg>
          </div>
          <p className="text-sm text-zinc-500 mt-2">This is a snippet of the content for Form 3...</p>
          <p className="text-xs text-zinc-400 mt-4">Last modified: 16 Nov 2023</p>
          <Button className="mt-4" variant="outline">
            Open Form
          </Button>
        </CardContent>
      </Card>
      <Card className="rounded-lg shadow-lg overflow-hidden">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <CardTitle className="font-semibold">Form Title 4</CardTitle>
            <svg
              className=" h-6 w-6 text-zinc-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect height="12" rx="2" width="20" x="2" y="6" />
              <path d="M12 12h.01" />
              <path d="M17 12h.01" />
              <path d="M7 12h.01" />
            </svg>
          </div>
          <p className="text-sm text-zinc-500 mt-2">This is a snippet of the content for Form 4...</p>
          <p className="text-xs text-zinc-400 mt-4">Last modified: 15 Nov 2023</p>
          <Button className="mt-4" variant="outline">
            Open Form
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}
