/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iSfsKtvFhGH
 */
import type { FormSchema } from "@prisma/client";
import dynamic from "next/dynamic";
const FormCard = dynamic(() => import("./FormCard"), { ssr: false });
type Props = {
  forms: FormSchema[];
};

export function FormCards({ forms }: Props) {
  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
      {forms.map((form) => {
        return <FormCard form={form} key={form.id} />;
      })}
    </div>
  );
}
