/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zSkLYeoqWgU
 */
import type { FormField, FormSchema } from "@prisma/client";
import React from "react";
import FormBuilderTopCard from "./FormBuilderTopCard";
import FormFieldAdderButtons from "./FormFieldAdderButtons";
import FormFieldRow from "./FormFieldRow";
import { api } from "@/utils/api";

type Props = {
  formSchema: FormSchema & {
    formFields: FormField[];
  };
};

export function FormBuilder({ formSchema }: Props) {
  const { data: formFields } = api.form.getAllFormFields.useQuery(
    {
      formSchemaId: formSchema.id,
    },
    {
      initialData: formSchema.formFields,
      staleTime: Infinity,
    },
  );
  return (
    <div className="">
      <FormBuilderTopCard name={formSchema.name} />

      <div className="h-8"></div>
      <div className="grid grid-cols-1 gap-4">
        <FormFieldAdderButtons formSchemaId={formSchema.id} />
        {formFields.map((formField) => {
          return <FormFieldRow formField={formField} key={formField.id} />;
        })}
      </div>
    </div>
  );
}
